# Generated by Django 3.1.2 on 2020-11-09 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('celular', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('clave', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('id_domiciliario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_orden',
            fields=[
                ('id_estado_orden', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('notas', models.CharField(max_length=255)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.cliente')),
                ('id_domiciliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.domiciliario')),
                ('id_estado_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.estado_orden')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=45)),
                ('valor_base', models.IntegerField()),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='orden_producto',
            fields=[
                ('id_producto_orden', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.SmallIntegerField()),
                ('valor_unitario', models.IntegerField()),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.orden')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.producto')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='id_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.sede'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('id_unidades_disponibles', models.SmallIntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.producto')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.IntegerField()),
                ('valor_domicilio', models.SmallIntegerField()),
                ('id_orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='floristeria.orden')),
            ],
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='id_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.sede'),
        ),
        migrations.CreateModel(
            name='categoria_producto',
            fields=[
                ('id_categoria_producto', models.AutoField(primary_key=True, serialize=False)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.categoria')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.producto')),
            ],
        ),
        migrations.CreateModel(
            name='carrito_producto',
            fields=[
                ('id_carrito_producto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.SmallIntegerField()),
                ('valor_unitario', models.IntegerField()),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.carrito')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.cliente'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='id_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.sede'),
        ),
    ]
