# Generated by Django 3.1.2 on 2020-12-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floristeria', '0002_administrador_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='username',
            field=models.CharField(default='NA', max_length=45),
        ),
    ]
