# Generated by Django 3.1.2 on 2020-10-30 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floristeria', '0003_categoria_categoria_producto_domiciliario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('clave', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('notas', models.CharField(max_length=255)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.cliente')),
                ('id_domiciliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.domiciliario')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.IntegerField()),
                ('valor_domicilio', models.SmallIntegerField()),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floristeria.orden', unique=True)),
            ],
        ),
    ]
