# Generated by Django 3.1.2 on 2020-12-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floristeria', '0004_auto_20201202_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='username',
            field=models.CharField(default='Usuario', max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(default='Usuario', max_length=45),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='username',
            field=models.CharField(default='Usuario', max_length=45),
        ),
    ]
